spring.datasource.url=jdbc:postgresql://dpg-crv7hq68ii6s738msmug-a.oregon-postgres.render.com/library_app_postsql_69ov
spring.datasource.username=library_app_postsql_69ov_user
spring.datasource.password=Wuh9UkNfGJuNm72wA9pQzOzdO2lgXhUT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
